### ISSUE TITLE
code doesn't work  sorry, it's ok

### ISSUE THREAD

**Issue by logiclj** [idiap/potr#9]
Sorry to bother you, when I run the program, the following problem occurs
[INFO] global 000171; step 0170; step_loss: 0.7252; lr: 0.00e+00 
[INFO] global 000181; step 0180; step_loss: 0.7251; lr: 0.00e+00 
[INFO] global 000191; step 0190; step_loss: 0.7287; lr: 0.00e+00 
epoch 0000; epoch_loss: 0.7207
Traceback (most recent call last):
  File "training/transformer_model_fn.py", line 206, in <module>
    model_fn.train()
  File "/root/pytorchtrans/potr-main/training/../training/seq2seq_model_fn.py", line 297, in train
    eval_loss = self.evaluate_fn(e, _time)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/root/pytorchtrans/potr-main/training/../training/seq2seq_model_fn.py", line 503, in evaluate_h36m
    decoder_pred = self._model(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/pytorchtrans/potr-main/data/../models/PoseTransformer.py", line 203, in forward
    return self.forward_autoregressive(
  File "/root/pytorchtrans/potr-main/data/../models/PoseTransformer.py", line 421, in forward_autoregressive
    pose_code = self._pose_embedding(pred_pose)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/pytorchtrans/potr-main/models/../models/PoseGCN.py", line 346, in forward
    B, S, D = x.size()
ValueError: not enough values to unpack (expected 3, got 2)

I don't know how to solve this problem, hope to get your help, thank you

**Comment by logiclj** [comment]
sorry, it's ok

**Comment by ytma1024** [comment]
Hello, I also met the same problem as you. May I ask how you solved it? Thank you very much.
![image](https://user-images.githubusercontent.com/50957474/208808990-8b13e7a5-ccdd-48c7-81c0-c222db06c363.png)
